name: Publish Release
on:
  release:
    types: [published]
jobs:
  zip:
    name: Attach ZIP asset
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.0
    - name: npm install and build
      run: |
        npm install
        composer install --no-dev --optimize-autoloader
        rm -rf node_modules package-lock.json .github .gitignore tests .editorconfig .nvmrc phpcs.xml.dist phpstan.neon.dist phpunit.xml.dist
        npm run archive
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{github.workspace}}/10up-snapshots.zip
        asset_name: 10up-snapshots.zip
        asset_content_type: application/zip