name: Test

env:
  COMPOSER_VERSION: "2"
  COMPOSER_CACHE: "${{ github.workspace }}/.composer-cache"

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - disable/*

jobs:
  phpunit_single_site:
    name: PHP Unit (Single Site)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Start MySQL
      run: sudo systemctl start mysql.service

    - name: Set standard 10up cache directories
      run: |
        composer config -g cache-dir "${{ env.COMPOSER_CACHE }}"

    - name: Prepare composer cache
      uses: actions/cache@v3
      with:
        path: ${{ env.COMPOSER_CACHE }}
        key: composer-${{ env.COMPOSER_VERSION }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-${{ env.COMPOSER_VERSION }}-

    - name: Set PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        coverage: none

    - name: Install dependencies
      run: composer install

    - name: Setup WP Tests
      run: |
        bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1
        sleep 10

    - name: PHPUnit
      run: |
        composer run-script test